Update post_chroot

diff --git a/post_chroot b/post_chroot
--- a/post_chroot
+++ b/post_chroot
@@ -31,14 +31,31 @@ echo -e "$rootpwd\n$rootpwd" | passwd
 sleep 2
 
 # Creating a user
-read -p "Type user name > " username
-read -p "Type user passwd > " userpwd
-useradd -m -g users -G wheel $username
-echo -e "$userpwd\n$userpwd" | passwd $username
-echo -e "$username ALL=(ALL) ALL" >> /etc/sudoers
-echo -e "%wheel    ALL=(ALL) ALL" >> /etc/sudoers
-echo -e "root    ALL=(ALL:ALL) ALL" >> /etc/sudoers
-sleep 2
+echo "
+Please Select:
+1. Create a user
+0. Quit
+"
+read -p "Enter selection [0-1] > "
+
+case "$REPLY" in
+0)	echo "Program terminated."
+	exit
+	;;
+1)	echo "User creation"
+	read -p "Type user name > " username
+	read -p "Type user passwd > " userpwd
+	useradd -m -g users -G wheel $username
+	echo -e "$userpwd\n$userpwd" | passwd $username
+	echo -e "$username ALL=(ALL) ALL" >> /etc/sudoers
+	echo -e "%wheel    ALL=(ALL) ALL" >> /etc/sudoers
+	echo -e "root    ALL=(ALL:ALL) ALL" >> /etc/sudoers
+	sleep 2
+	;;
+*)	echo "Invalid entry" >&2
+	exit 1
+	;;
+esac
 
 # Instaling and configuring GRUB
 if [ "$BOOT" == "bios" ]; then 
