option to install xfce

diff --git a/post_chroot b/post_chroot
--- a/post_chroot
+++ b/post_chroot
@@ -75,6 +75,25 @@ grub-mkconfig -o /boot/grub/grub.cfg
 sleep 2
 
 # Finishing
+echo "
+Install xfce?
+1. Yes
+0. No
+"
+
+read -xfce "Enter selection [0-1] > "
+
+case "$xfce" in
+0)	echo "Continue installation."
+	;;
+1)	echo "Installing xfce"
+	pacman -S xorg xfce4 xfce4-goodies lightdm lightdm-gtk-greeter
+	systemctl enable lightdm
+	sleep 2
+	;;
+*)	echo "Invalid entry" >&2
+	;;
+esac
 systemctl enable NetworkManager.service
 exit
 umount -R /mnt
